name: log4dart
version: 1.4.8
author: Lars Tackmann <lars@solvr.io>
description: Logging library with multiple appenders, configurable formatting and log tracing.
homepage: https://github.com/ltackmann/log4dart
environment:
  sdk: '>=0.5.20'
dependencies:
  meta: '>=0.5.20'
  sprintf: '>=1.0.7 <2.0.0'
dev_dependencies:
  unittest: any
