name: log4dart
version: 1.4.5
author: Lars Tackmann <lars@solvr.io>
description: Logging library with multiple appenders, configurable formatting and log tracing.
homepage: https://github.com/ltackmann/log4dart
dependencies:
  sprintf: '>=1.0.6 <2.0.0'
  meta: '>=0.4.0'
dev_dependencies:
  unittest: any
environment:
  sdk: ">=0.4.7"
