name: log4dart
version: 1.4.11
author: Lars Tackmann <lars@solvr.io>
description: Logging library with multiple appenders, configurable formatting and log tracing.
homepage: https://github.com/ltackmann/log4dart
environment:
  sdk: '>=0.8.7'
dependencies:
  meta: '>=0.8.7'
  sprintf: '>=1.0.8'
dev_dependencies:
  unittest: any
