name: log4dart
version: 2.0.0-dev
author: Lars Tackmann <lars@solvr.io>
description: Logging library with multiple appenders, configurable formatting and log tracing.
homepage: https://github.com/ltackmann/log4dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  sprintf: ^4.0.0
dev_dependencies:
  test: ^1.3.0
