name: log4dart
version: 1.4.1
author: Lars Tackmann <lars@solvr.io>
description: Powerful logging library with support for multiple appenders, configurable formatting and log tracing.
homepage: https://github.com/ltackmann/log4dart
dependencies:
  meta: 0.4.3+1
  sprintf: ">=1.0.5 <2.0.0"
dev_dependencies:
  unittest: any
  
