name: log4dart
version: 1.3.2
author: Lars Tackmann <lars@solvr.io>
description: Powerful logging library for Dart with support for multiple appenders, configurable formatting and log tracing using diagnostic contexts. .
homepage: https://github.com/ltackmann/log4dart
dependencies:
  sprintf: '>=1.0.3 <2.0.0'
  
dev_dependencies:
  unittest: any
  
