name: log4dart
author: [Lars Tackmann <lars@solvr.io>, Adam Singer <adam@solvr.io>]
homepage: https://github.com/Solvr/log4dart
description: >
  A powerful logger for Dart with support for multiple appenders, 
  diagnostic context and configurable formatting. 
version: 1.1.0   
dependencies:
  sprintf: any