name: log4dart
version: 1.4.17
author: Lars Tackmann <lars@solvr.io>
description: Logging library with multiple appenders, configurable formatting and log tracing.
homepage: https://github.com/ltackmann/log4dart
dependencies:
  meta: "^0.8.8"
  sprintf: "^1.0.8"
dev_dependencies:
  test: any
